name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run test on docker-compose
      run: |
        docker-compose up -d
        docker-compose exec -i web python manage.py migrate
        docker-compose exec -i web python manage.py test